### ISSUE TITLE
Difference between Env class signature and members

### ISSUE THREAD

**Issue by stephenpcook** [hunterakins/pyat#10]
On the `Env` class it attempts to initialise `SSP_array` but it isn't defined.

https://github.com/hunterakins/pyat/blob/07565471cb2f76b92fbb05746fb9d08bfd6d05c3/pyat/env.py#L154-L164

I thought it might be a member of `SSP`, i.e. `SSP.array`, but it's not defined in [that class definition](https://github.com/hunterakins/pyat/blob/07565471cb2f76b92fbb05746fb9d08bfd6d05c3/pyat/env.py#L74-L83) either.

The argument `bndy` is not used - perhaps this is related to be `SSP_array`?

Note `Env` doesn't actually seem to be used in any of the code at the moment, so this might not even be an issue.

**Comment by hunterakins** [comment]
Yes I think I had dreams of making an Env object that to manage the whole model setup, but ended up moving it to a different project. I will get rid of it here.
