### ISSUE TITLE
Axis units

### ISSUE THREAD

**Issue by mzzmrt** [hunterakins/pyat#13]
Hi,

I have installed acoustic toolbox and pyat and they are working.

When I run bellhop cases in pyat /test directory got reasonable looking results, on the other hand plotted results show 200 units on z axis and  1.000 units on x axis although according the .env file they are 5.000 meters and 100 km. Am I missing something? I am using latest version of at by the way.

Regards,

**Comment by hunterakins** [comment]
The axis units aren't labeled in the plotting in the test script and the domain points aren't passed in. 
The axes are just the x and z grid indices.
