### ISSUE TITLE
Is the repository open for contributions?

### ISSUE THREAD

**Issue by stephenpcook** [hunterakins/pyat#7]
I have seen some places where I could make some potential improvements, and would like to use some of the code in a project. Is this repo intended for public use, and would you welcome pull requests?

If so, it should probably have a license file (see https://choosealicense.com/) and perhaps a contributing file.

For the license, depending on how much the code is tied in with AT or AcTUP, it may be a requirement to use a GPL license.

**Comment by hunterakins** [comment]
I originally wrote it for my own use, but shared it to spare others from the tedium of translating the MATLAB interface. 
I would welcome pull requests. 
I wrote it while at UC San Diego (still there), and have been unsuccessfully trying to get help with licensing from the IP support. If you are knowledgeable about licensing, I would like to discuss this with you. I will shoot you an email to follow up.

**Comment by stephenpcook** [comment]
Re 07565471cb2f76b92fbb05746fb9d08bfd6d05c3, I think GPL was probably the appropriate license due to the "AT to AcTUP to this" chain, with AT being GPL (then copyleft forcing the issue on derivatives/modifications).

I'll work on a PR for some minor issues I've come across. Thanks for your speedy response on this!
