### ISSUE TITLE
Minor errors that probably aren't even met in normal usage

### ISSUE THREAD

**Issue by stephenpcook** [hunterakins/pyat#8]
The small modifications I was talking about in #7 are pretty minor, and probably not even met in normal usage.

For example, the file-exists error in `read_shd_bin` https://github.com/hunterakins/pyat/blob/07565471cb2f76b92fbb05746fb9d08bfd6d05c3/pyat/readwrite.py#L413-L415
is not a python error, however it's never hit because the first line raises the appropriate exception. 

The `linspace` commands and the indexing on
https://github.com/hunterakins/pyat/blob/07565471cb2f76b92fbb05746fb9d08bfd6d05c3/pyat/readwrite.py#L444-L451
are wrong (`linspace(pos.s.x(1), pos.s.x(end), Nsx )` should probably be `np.linspace(pos.s.x[0], pos.s.x[-1], Nsx)`), but again, perhaps these aren't hit?

And there isn't a function for `read_shd_asc` as in
https://github.com/hunterakins/pyat/blob/07565471cb2f76b92fbb05746fb9d08bfd6d05c3/pyat/readwrite.py#L678-L679
but maybe it should just raise a [`NotImplementedError`](https://docs.python.org/3/library/exceptions.html#NotImplementedError)?

I think there was another edge case which I caught, based on a misnamed argument, but again, not sure if it gets hit.

I can create a PR with these changes to clean up those sections slightly, but since I don't think it affects behaviour it's your decision - let me know if you want the PR.

**Comment by hunterakins** [comment]
Yes the first two look line Matlab lines that I guess I never translated. 
I would accept the PR, will be nice when someone eventually does hit these...
